spring:
  application:
    name: nekodion-batch
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3368/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
